"""
Query Planner: LLM-driven plan-execute-evaluate retrieval loop.

Instead of hardcoding which retrieval strategies to run and how to combine
them, the query planner lets an LLM generate a structured retrieval plan
based on the available indexes and the user's query.  When results are
insufficient the LLM diagnoses *why* and generates a revised plan — changing
indexes, parameters, or combination strategy rather than just rewriting the
query text.

Enable via ``RetrieverConfig(use_query_planner=True)``.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Callable
from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING, Any

import numpy as np

from zerogmem.defaults import llm_chat_kwargs

if TYPE_CHECKING:
    from zerogmem.retriever.query_analyzer import QueryAnalysis
    from zerogmem.retriever.retriever import RetrievalResult

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


class CombineStrategy(Enum):
    """How to merge results from multiple plan steps."""

    RRF = "rrf"
    UNION = "union"
    INTERSECT = "intersect"


@dataclass
class IndexDescriptor:
    """Natural-language description of an index for the LLM planner."""

    name: str
    description: str
    parameters: dict[str, str]  # param_name → description
    available: bool = True


@dataclass
class PlanStep:
    """A single step in a query plan."""

    step_id: int
    index_name: str
    query_override: str | None = None
    params: dict[str, Any] = field(default_factory=dict)
    depends_on: list[int] = field(default_factory=list)
    rationale: str = ""


@dataclass
class QueryPlan:
    """A complete retrieval plan generated by the LLM."""

    steps: list[PlanStep]
    combine: CombineStrategy = CombineStrategy.RRF
    rationale: str = ""


# ---------------------------------------------------------------------------
# Index adapter
# ---------------------------------------------------------------------------


class IndexAdapter:
    """Wraps a Retriever strategy method for uniform dispatch."""

    def __init__(self, name: str, execute_fn: Callable[..., list[Any]]):
        self.name = name
        self._execute_fn = execute_fn

    def execute(
        self,
        query: str,
        query_embedding: np.ndarray | None,
        analysis: QueryAnalysis,
        params: dict[str, Any],
    ) -> list[RetrievalResult]:
        """Call the wrapped strategy. Returns [] on error."""
        try:
            return self._execute_fn(
                query=query,
                query_embedding=query_embedding,
                analysis=analysis,
                params=params,
            )
        except Exception:
            logger.exception("IndexAdapter '%s' failed", self.name)
            return []


# ---------------------------------------------------------------------------
# Index registry
# ---------------------------------------------------------------------------


class IndexRegistry:
    """Holds available index adapters and their LLM-facing descriptions."""

    def __init__(self) -> None:
        self._adapters: dict[str, IndexAdapter] = {}
        self._descriptors: dict[str, IndexDescriptor] = {}

    def register(self, descriptor: IndexDescriptor, adapter: IndexAdapter) -> None:
        self._descriptors[descriptor.name] = descriptor
        self._adapters[descriptor.name] = adapter

    def get_adapter(self, name: str) -> IndexAdapter | None:
        return self._adapters.get(name)

    def available_descriptors(self) -> list[IndexDescriptor]:
        return [d for d in self._descriptors.values() if d.available]

    def available_names(self) -> list[str]:
        return [d.name for d in self._descriptors.values() if d.available]

    def describe_for_llm(self) -> str:
        """Format available indexes as text for the planner prompt."""
        lines: list[str] = []
        for desc in self.available_descriptors():
            params_str = ", ".join(
                f"{k} ({v})" for k, v in desc.parameters.items()
            ) or "none"
            lines.append(f"- **{desc.name}**: {desc.description}  Params: {params_str}.")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

_PLANNER_SYSTEM = """\
You are a retrieval planner for a conversational memory system.
Given a question and available indexes, produce a retrieval plan as JSON.

Available indexes:
{index_descriptions}

Output JSON (no markdown fences):
{{
  "rationale": "brief reasoning",
  "combine": "rrf" | "union" | "intersect",
  "steps": [
    {{
      "step_id": 1,
      "index_name": "<name>",
      "query_override": null or "alt query",
      "params": {{}},
      "depends_on": [],
      "rationale": "why"
    }}
  ]
}}

Guidelines:
- Use 4-8 steps. More strategies = better recall via RRF fusion.
- ALWAYS include "semantic" and "bm25" as your foundation (these two catch most facts).
- ALWAYS include "fact" (covers personal attributes/preferences).
- Add "entity" when specific people/places are mentioned.
- Add "temporal" when dates/times/ordering matter.
- Add "graph" for multi-hop or causal reasoning.
- Add "working_memory" for recent context.
- Add "hierarchical" when scoping to conversation segments.
- Set query_override when a step needs a different search angle (e.g., decompose multi-hop questions).
- For counting questions, set top_k to 30+ to capture all instances.
- When in doubt, include more indexes — RRF fusion handles noise well.
- When expected_answer_type is "list" or the question asks for multiple attributes/items
  ("what traits/hobbies/books does X have", "list all Y", "what are X's ..."),
  this is an EXHAUSTIVE ENUMERATION query. You MUST:
  1. Use entity index with high top_k_per_entity (20+) and source_filter to retrieve ALL matching
     memories (e.g. source_filter="personality_trait" for personality traits).
  2. Use multiple bm25 steps with varied query_overrides to catch different phrasings.
  3. Use combine="union" instead of "rrf" so no relevant items are lost to rank fusion.

Example plan for "What personality traits might Alice say Bob has?":
{{
  "rationale": "Exhaustive enumeration of traits — need entity search with trait filter + broad BM25",
  "combine": "union",
  "steps": [
    {{"step_id": 1, "index_name": "entity", "query_override": null,
      "params": {{"entities": ["Bob", "Alice"], "top_k_per_entity": 25, "source_filter": "personality_trait"}},
      "depends_on": [], "rationale": "Get all personality trait memories for Bob"}},
    {{"step_id": 2, "index_name": "entity", "query_override": null,
      "params": {{"entities": ["Bob", "Alice"], "top_k_per_entity": 15}},
      "depends_on": [], "rationale": "Get general entity memories about Bob from Alice"}},
    {{"step_id": 3, "index_name": "semantic", "query_override": null, "params": {{"top_k": 30}},
      "depends_on": [], "rationale": "Semantic search for trait descriptions"}},
    {{"step_id": 4, "index_name": "bm25", "query_override": "Bob personality traits",
      "params": {{}}, "depends_on": [], "rationale": "BM25 for personality keywords"}},
    {{"step_id": 5, "index_name": "bm25", "query_override": "Alice describes Bob",
      "params": {{}}, "depends_on": [], "rationale": "BM25 for Alice describing Bob"}},
    {{"step_id": 6, "index_name": "fact", "query_override": null, "params": {{}},
      "depends_on": [], "rationale": "Fact index for attribute facts"}}
  ]
}}
"""

_EVALUATOR_SYSTEM = """\
You evaluate whether retrieved results can answer a question.
Respond with JSON (no markdown fences):
{{
  "sufficient": true/false,
  "confidence": 0.0-1.0,
  "diagnosis": "what specific information is missing" or null
}}
"""

_REPLAN_ADDENDUM = """
[REPLAN] The previous plan did not produce sufficient results.
Diagnosis: {diagnosis}
Previous steps tried: {previous_steps}
Result counts per step: {step_counts}

Generate a REVISED plan addressing the gaps. Try different query angles or indexes.
"""


# ---------------------------------------------------------------------------
# Query planner
# ---------------------------------------------------------------------------


class QueryPlanner:
    """LLM-driven plan → execute → evaluate → replan loop."""

    def __init__(
        self,
        registry: IndexRegistry,
        llm_client: Any,
        llm_model: str,
        max_rounds: int = 2,
        rrf_fn: Callable | None = None,
        rrf_k: int = 60,
    ) -> None:
        self.registry = registry
        self.llm_client = llm_client
        self.llm_model = llm_model
        self.max_rounds = max_rounds
        self._rrf_fn = rrf_fn
        self._rrf_k = rrf_k

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def plan_and_execute(
        self,
        query: str,
        query_embedding: np.ndarray | None,
        analysis: QueryAnalysis,
    ) -> tuple[list[Any], dict[str, Any]]:  # (results, metadata)
        """Full plan-execute-evaluate loop. Returns (merged results, metadata)."""
        all_results: list[Any] = []
        failure_diagnosis: str | None = None
        previous_step_names: list[str] = []
        previous_step_counts: dict[str, int] = {}
        final_sufficient = False
        rounds_used = 0

        for round_num in range(1, self.max_rounds + 1):
            rounds_used = round_num

            # Generate plan
            plan = self._generate_plan(
                query,
                analysis,
                previous_results=all_results if round_num > 1 else None,
                failure_diagnosis=failure_diagnosis,
                previous_steps=previous_step_names,
                previous_step_counts=previous_step_counts,
            )
            logger.info(
                "Query planner round %d: %d steps, combine=%s — %s",
                round_num,
                len(plan.steps),
                plan.combine.value,
                plan.rationale,
            )
            for step in plan.steps:
                logger.debug(
                    "  Step %d: %s query_override=%s params=%s",
                    step.step_id, step.index_name,
                    step.query_override, step.params,
                )

            # Execute plan
            step_results = self._execute_plan(plan, query, query_embedding, analysis)

            # Track what we've tried
            for step in plan.steps:
                if step.index_name not in previous_step_names:
                    previous_step_names.append(step.index_name)
            previous_step_counts.update(
                {k: len(v) for k, v in step_results.items()}
            )

            # Combine results
            combined = self._combine_results(step_results, plan, analysis)

            # Merge with prior rounds (dedup by id)
            seen_ids = {r.id for r in all_results}
            for r in combined:
                if r.id not in seen_ids:
                    all_results.append(r)
                    seen_ids.add(r.id)

            # Evaluate
            sufficient, diagnosis = self._evaluate_results(
                query, step_results, plan
            )
            logger.info(
                "Query planner round %d evaluation: sufficient=%s, diagnosis=%s",
                round_num, sufficient, diagnosis,
            )

            if sufficient:
                final_sufficient = True
                break

            failure_diagnosis = diagnosis

        # Sort by score descending
        all_results.sort(key=lambda r: r.score, reverse=True)

        metadata = {
            "sufficient": final_sufficient,
            "rounds_used": rounds_used,
            "failure_diagnosis": failure_diagnosis or "",
        }
        return all_results, metadata

    # ------------------------------------------------------------------
    # Plan generation
    # ------------------------------------------------------------------

    def _generate_plan(
        self,
        query: str,
        analysis: QueryAnalysis,
        previous_results: list[Any] | None = None,
        failure_diagnosis: str | None = None,
        previous_steps: list[str] | None = None,
        previous_step_counts: dict[str, int] | None = None,
    ) -> QueryPlan:
        """LLM generates a retrieval plan as JSON."""
        system_msg = _PLANNER_SYSTEM.format(
            index_descriptions=self.registry.describe_for_llm(),
        )

        user_parts = [
            f"Question: {query}",
            f"Intent: {analysis.intent.value}",
            f"Reasoning type: {analysis.reasoning_type.value}",
            f"Expected answer type: {analysis.expected_answer_type}",
            f"Entities: {', '.join(analysis.entities) if analysis.entities else 'none'}",
            f"Temporal scope: {analysis.temporal_scope.value}",
            f"Keywords: {', '.join(analysis.keywords) if analysis.keywords else 'none'}",
        ]

        if failure_diagnosis:
            user_parts.append(
                _REPLAN_ADDENDUM.format(
                    diagnosis=failure_diagnosis,
                    previous_steps=", ".join(previous_steps or []),
                    step_counts=json.dumps(previous_step_counts or {}),
                )
            )

        user_msg = "\n".join(user_parts)

        try:
            response = self.llm_client.chat.completions.create(
                **llm_chat_kwargs(self.llm_model, max_tokens=1200, temperature=0),
                messages=[
                    {"role": "system", "content": system_msg},
                    {"role": "user", "content": user_msg},
                ],
            )
            text = (response.choices[0].message.content or "").strip()
            logger.debug(
                "Plan LLM raw response (first 500 chars): %s",
                text[:500] if text else "(empty)",
            )
            if not text:
                logger.warning(
                    "Plan LLM returned empty response, finish_reason=%s",
                    getattr(response.choices[0], "finish_reason", "unknown"),
                )
            return self._parse_plan(text)
        except Exception:
            logger.exception("Query planner LLM call failed, using default plan")
            return self._default_plan(analysis)

    def _parse_plan(self, text: str) -> QueryPlan:
        """Parse LLM JSON response into a QueryPlan."""
        # Strip markdown fences if present
        if text.startswith("```"):
            first_nl = text.index("\n") if "\n" in text else 3
            text = text[first_nl:].strip()
        if text.endswith("```"):
            text = text[:-3].strip()

        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            logger.warning("Failed to parse plan JSON (first 300 chars): %s", text[:300])
            return self._default_plan_from_text()

        # Parse combination strategy
        combine_str = data.get("combine", "rrf").lower()
        try:
            combine = CombineStrategy(combine_str)
        except ValueError:
            combine = CombineStrategy.RRF

        # Parse steps
        available = set(self.registry.available_names())
        steps: list[PlanStep] = []
        for raw_step in data.get("steps", []):
            index_name = raw_step.get("index_name", "")
            if index_name not in available:
                logger.warning("Plan references unknown index '%s', skipping", index_name)
                continue
            steps.append(
                PlanStep(
                    step_id=raw_step.get("step_id", len(steps) + 1),
                    index_name=index_name,
                    query_override=raw_step.get("query_override"),
                    params=raw_step.get("params", {}),
                    depends_on=raw_step.get("depends_on", []),
                    rationale=raw_step.get("rationale", ""),
                )
            )

        if not steps:
            logger.warning("Plan has no valid steps, using default")
            return self._default_plan_from_text()

        return QueryPlan(
            steps=steps,
            combine=combine,
            rationale=data.get("rationale", ""),
        )

    def _default_plan(self, analysis: QueryAnalysis | None = None) -> QueryPlan:
        """Fallback plan: query all available indexes with RRF."""
        steps = []
        for i, name in enumerate(self.registry.available_names(), start=1):
            steps.append(
                PlanStep(
                    step_id=i,
                    index_name=name,
                    rationale="default fallback — query all indexes",
                )
            )
        return QueryPlan(
            steps=steps,
            combine=CombineStrategy.RRF,
            rationale="Default plan (LLM plan generation failed)",
        )

    def _default_plan_from_text(self) -> QueryPlan:
        """Shorthand for default plan without analysis."""
        return self._default_plan(None)

    # ------------------------------------------------------------------
    # Plan execution
    # ------------------------------------------------------------------

    def _execute_plan(
        self,
        plan: QueryPlan,
        query: str,
        query_embedding: np.ndarray | None,
        analysis: QueryAnalysis,
    ) -> dict[str, list[Any]]:
        """Execute each plan step. Returns {step_key: results}."""
        step_results: dict[str, list[Any]] = {}

        # Topological sort by depends_on (simple: independent first, then dependent)
        executed: set[int] = set()
        remaining = list(plan.steps)
        max_iterations = len(remaining) + 1  # prevent infinite loop

        for _ in range(max_iterations):
            if not remaining:
                break
            next_batch = [
                s for s in remaining
                if all(d in executed for d in s.depends_on)
            ]
            if not next_batch:
                # Remaining steps have unresolvable dependencies — run them anyway
                logger.warning("Unresolvable dependencies in plan, executing remaining steps")
                next_batch = remaining

            for step in next_batch:
                adapter = self.registry.get_adapter(step.index_name)
                if adapter is None:
                    logger.warning("No adapter for index '%s'", step.index_name)
                    continue

                effective_query = step.query_override or query
                results = adapter.execute(
                    query=effective_query,
                    query_embedding=query_embedding,
                    analysis=analysis,
                    params=step.params,
                )
                key = f"{step.index_name}_{step.step_id}"
                step_results[key] = results
                executed.add(step.step_id)

                logger.debug(
                    "Plan step %d (%s): %d results",
                    step.step_id, step.index_name, len(results),
                )

            remaining = [s for s in remaining if s.step_id not in executed]

        return step_results

    # ------------------------------------------------------------------
    # Result combination
    # ------------------------------------------------------------------

    def _combine_results(
        self,
        step_results: dict[str, list[Any]],
        plan: QueryPlan,
        analysis: QueryAnalysis | None = None,
    ) -> list[Any]:
        """Combine per-step results according to the plan's strategy."""
        if plan.combine == CombineStrategy.RRF and self._rrf_fn:
            # Reuse Retriever's RRF fusion
            # _rrf_fn expects dict[str, list[RetrievalResult]] and analysis
            return self._rrf_fn(step_results, analysis)

        if plan.combine == CombineStrategy.INTERSECT:
            return self._intersect(step_results)

        # Default: UNION (dedup merge)
        return self._union(step_results)

    @staticmethod
    def _union(step_results: dict[str, list[Any]]) -> list[Any]:
        """Merge all results, dedup by id, keep highest score."""
        seen: dict[str, Any] = {}
        for results in step_results.values():
            for r in results:
                if r.id not in seen or r.score > seen[r.id].score:
                    seen[r.id] = r
        merged = list(seen.values())
        merged.sort(key=lambda r: r.score, reverse=True)
        return merged

    @staticmethod
    def _intersect(step_results: dict[str, list[Any]]) -> list[Any]:
        """Keep only results appearing in ALL steps. Score = sum of scores."""
        if not step_results:
            return []

        # Count occurrences and accumulate scores
        id_scores: dict[str, float] = {}
        id_items: dict[str, Any] = {}
        id_counts: dict[str, int] = {}
        num_steps = len(step_results)

        for results in step_results.values():
            for r in results:
                id_scores[r.id] = id_scores.get(r.id, 0.0) + r.score
                id_items[r.id] = r
                id_counts[r.id] = id_counts.get(r.id, 0) + 1

        # Keep only items in all steps
        intersected = []
        for rid, count in id_counts.items():
            if count >= num_steps:
                item = id_items[rid]
                item.score = id_scores[rid]
                intersected.append(item)

        intersected.sort(key=lambda r: r.score, reverse=True)
        return intersected

    # ------------------------------------------------------------------
    # Evaluation
    # ------------------------------------------------------------------

    def _evaluate_results(
        self,
        query: str,
        step_results: dict[str, list[Any]],
        plan: QueryPlan,
    ) -> tuple[bool, str]:
        """LLM evaluates whether results are sufficient. Returns (sufficient, diagnosis)."""
        # Build summary
        total = sum(len(v) for v in step_results.values())
        per_step_lines = []
        for key, results in step_results.items():
            per_step_lines.append(f"  {key}: {len(results)} results")

        # Preview top results
        all_combined = self._union(step_results)
        top_preview = []
        for r in all_combined[:5]:
            snippet = r.content[:150].replace("\n", " ")
            top_preview.append(f"  - [{r.source}] {snippet}")

        user_msg = (
            f"Question: {query}\n\n"
            f"Results summary ({total} total):\n"
            + "\n".join(per_step_lines)
            + "\n\nTop 5 results:\n"
            + "\n".join(top_preview) if top_preview else "  (no results)"
        )

        try:
            response = self.llm_client.chat.completions.create(
                **llm_chat_kwargs(self.llm_model, max_tokens=150, temperature=0),
                messages=[
                    {"role": "system", "content": _EVALUATOR_SYSTEM},
                    {"role": "user", "content": user_msg},
                ],
            )
            text = (response.choices[0].message.content or "").strip()
            return self._parse_evaluation(text, total)
        except Exception:
            logger.exception("Query planner evaluation LLM call failed, treating as sufficient")
            return True, ""

    @staticmethod
    def _parse_evaluation(text: str, total_results: int) -> tuple[bool, str]:
        """Parse evaluator JSON response."""
        # Strip markdown fences
        if text.startswith("```"):
            first_nl = text.index("\n") if "\n" in text else 3
            text = text[first_nl:].strip()
        if text.endswith("```"):
            text = text[:-3].strip()

        try:
            data = json.loads(text)
            sufficient = bool(data.get("sufficient", total_results > 0))
            diagnosis = data.get("diagnosis", "") or ""
            return sufficient, diagnosis
        except json.JSONDecodeError:
            # If we can't parse, default to sufficient if we have results
            return total_results > 0, ""
